### ISSUE TITLE
Monet Theming Engine Regression [Duplicate]

### ISSUE THREAD

**Issue by KoremuMekuro** [crdroidandroid/android_packages_apps_crDroidSettings#1041]
With 9.3, firstly on redmi note 8t and then on poco f3 with second 9.3 update I noticed that with this update changed theming options and I can't have vibrant colors anymore.Only with proprietary repainter I can achive vibrant colors.
Why that was changed?Is there any hope that old theming option will be returned?Or maybe there will be added options, so it will be possible to achive vibrant colors?I created duplicate here, cuz idk where I'm supposed to open such issue and where someone will notice it faster(crdroid_features with the latest activity from Nov 19, 2022, issue_tracker or here).
![Screenshot_20230407-192142_Settings](https://user-images.githubusercontent.com/125179297/230664603-2f7ee85c-31bd-4420-80bb-6627f63c13a4.png)

**Comment by gwolf2u** [comment]
this is fixed

**Comment by KoremuMekuro** [comment]
> this is fixed

No.This i
![Screenshot_20230407-192142_Settings](https://user-images.githubusercontent.com/125179297/230643193-3c0dfd91-fcf6-480b-ac0f-335eee9d402b.png)
sn't fixed.On poco f3 update was only a day ago.And in the commit there are still the same options from this 9.3 update and not from march 31st 9.3 or 9.2 and earlier.Or maybe I have to downgrade and show that settings are changed and there are producing much worse result than it was before.
